### PR TITLE
Implement regime authorisation fully

### PR DESCRIPTION
**Pull request by Cruikshanks**
Currently, our authorisation mimics how authorisation should happen. It handles admin and public requests. But requests to 'regime' endpoints we mimic with a simple check that the username matches the requested regime.

What it should actually be doing is checking the requested regime against the regimes the system user is linked to.

Now we have the `RegimeModel` and `AuthorisedSystemModel` properly linked via [Objection](https://github.com/vincit/objection.js) we can do this.

This change adds a new service to handle the checking. We also needed to add a new regimes test helper to support this.

Another feature is we have to query the database for the regime as part of the checking. To avoid subsequent endpoints needing to do this we stash the `RegimeModel` instance in [request.app](https://hapi.dev/api/?v=20.0.2#-requestapp).

### CODE REVIEW

**Comment by Cruikshanks** [comment]
Will get #58 merged in, rebase this branch, then ask for a review!

**Review by StuAA78 — CHANGES_REQUESTED** [review]
Elsewhere (eg. `regimes.controller`) we return the results of database queries without first putting them into a variable -- do we want to do this here as well?

**Comment by Cruikshanks** [comment]
> Elsewhere (eg. `regimes.controller`) we return the results of database queries without first putting them into a variable -- do we want to do this here as well?

Does this cover what you were thinking of @StuAA78 ?

The one other place I can think it applies is

```javascript
// ...
const regime = await this._userAuthorisedRegime(user, regimeSlug)
if (regime) {
  result.authorised = true
  result.regime = regime
}
// ..
```

I was initially returning the result of `_userAuthorisedRegime()` into `result.regime`. But my unit tests exposed when no regime match is found we get `undefined` and I want to explicitly return `null` in the `result` object.

Let me know what you think 🤷‍♂️

**Comment by Cruikshanks** [comment]
Ahh @StuAA78 ! Saw your other comms. Think I've covered it now 👍

**Review by StuAA78 — APPROVED** [review]

**Pull request merged**
